#pragma once

#include <gflags/gflags.h>

namespace dairlib {

DECLARE_double(kp);
DECLARE_double(kd);
DECLARE_double(tau_max);
DECLARE_double(contact_force_thresh);
DECLARE_double(penetration_index_middle);
DECLARE_double(penetration_thumb);
DECLARE_double(tip_surface_offset_z);
DECLARE_double(ring_tip_surface_offset_z);
DECLARE_double(ring_tip_surface_offset_y);
DECLARE_bool(track_cube_contact);
DECLARE_bool(contact_force_log);
DECLARE_double(contact_force_log_hz);
DECLARE_bool(lcm_publish);
DECLARE_double(lcm_publish_hz);
DECLARE_bool(isolate_cube);
DECLARE_double(contact_enable_t);
DECLARE_double(t_contact);
DECLARE_double(handoff_settle_time);
DECLARE_double(k_hold);
DECLARE_double(w_cube);
DECLARE_double(w_cube_vel);
DECLARE_double(w_vel);
DECLARE_double(w_R);
DECLARE_double(w_G);
DECLARE_double(w_U);
DECLARE_double(w_lambda);
DECLARE_double(alpha_m);
DECLARE_string(cube_motion_mode);
DECLARE_double(cube_move_dx);
DECLARE_double(cube_move_dy);
DECLARE_double(cube_move_dz);
DECLARE_double(cube_move_roll);
DECLARE_double(cube_move_pitch);
DECLARE_double(cube_move_yaw);
DECLARE_double(cube_move_period);
DECLARE_double(cube_move_duration);
DECLARE_double(cube_ik_lead_pos_max);
DECLARE_double(cube_ik_lead_rot_max);
DECLARE_bool(show_cube_target);
DECLARE_bool(show_cube_start);
DECLARE_bool(rot_log);
DECLARE_double(rot_log_period);
DECLARE_bool(lambda_map_debug);
DECLARE_bool(plan_debug);
DECLARE_bool(c3_joint_plan_log);
DECLARE_bool(osc_torque_split_log);
DECLARE_double(task_kp);
DECLARE_double(task_kd);
DECLARE_string(exec_mode);
DECLARE_string(osc_target_source);
DECLARE_double(osc_kp);
DECLARE_double(osc_kd);
DECLARE_double(osc_qd_filter_tau);
DECLARE_bool(exec_grav_comp);
DECLARE_double(force_floor);
DECLARE_double(lambda_torque_scale);
DECLARE_bool(fk_target);
DECLARE_int32(N);
DECLARE_double(c3_dt);
DECLARE_double(mu);
DECLARE_int32(num_friction_directions);
DECLARE_string(contact_model);
DECLARE_double(input_scale);
DECLARE_bool(relinearize);
DECLARE_bool(warm_start_admm);
DECLARE_int32(c3_period_steps);
DECLARE_int32(relin_period_steps);
DECLARE_int32(track_ik_period_steps);
DECLARE_double(osqp_eps);
DECLARE_int32(admm_iter);
DECLARE_double(rho_scale);
DECLARE_bool(warm_start);
DECLARE_bool(release_middle);
DECLARE_string(release_finger);
DECLARE_double(release_middle_t);
DECLARE_double(release_middle_offset);
DECLARE_double(regrasp_settle_time);
DECLARE_double(regrasp_duration);
DECLARE_double(regrasp_touch_tol);
DECLARE_double(regrasp_arc_clearance);
DECLARE_double(release_middle_tri_spread);
DECLARE_double(release_middle_tri_base_z);
DECLARE_double(release_middle_tri_apex_z);
DECLARE_bool(gait);
DECLARE_double(gait_delta);
DECLARE_int32(gait_cycles);
DECLARE_double(gait_rotate_duration);
DECLARE_string(gait_scheme);
DECLARE_double(spider_yaw_delta);
DECLARE_double(spider_yaw_duration);
DECLARE_double(spider_ring_red_y);
DECLARE_double(spider_ring_hold_z);
DECLARE_double(relay_ring_hold_z);
DECLARE_double(relay_ring_press);
DECLARE_double(relay_ring_retract);
DECLARE_bool(gait_realign);
DECLARE_bool(gait_log);
DECLARE_bool(gait_handoff_debug);
DECLARE_double(gait_log_period);
DECLARE_bool(legacy_log);
DECLARE_int32(gait_seek_period_steps);
DECLARE_double(gait_leg_gap);
DECLARE_double(gait_touch_offset);
DECLARE_double(gait_touch_duration);
DECLARE_int32(gait_rebuild_solve_passes);
DECLARE_double(gait_force_ramp_time);
DECLARE_double(gait_torque_ramp_time);
DECLARE_double(gait_leg_timeout);
DECLARE_double(gait_hold_time);
DECLARE_double(cube_start_x);
DECLARE_double(cube_start_y);
DECLARE_double(cube_start_z);
DECLARE_bool(preview);
DECLARE_double(sim_time);

// Validates cross-flag invariants and applies the gait topology normalization.
// Throws std::runtime_error for invalid combinations.
void ValidateAndNormalizeSqueezeFlags();

}  // namespace dairlib
